apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI=       # base64 of "app_user"
  db_pass: U3Ryb25nU0BwYXNzdzByZCE=  # base64 of "StrongP@ssw0rd!"
  jwt_secret: c3VwZXJzZWNyZXRrZXk= # base64 of "supersecretkey"

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI=
  db_pass: U3Ryb25nU0BwYXNzdzByZCE=

---
apiVersion: v1
kind: Secret
metadata:
  name: seating-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI=
  db_pass: U3Ryb25nU0BwYXNzdzByZCE=

---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI=
  db_pass: U3Ryb25nU0BwYXNzdzByZCE=

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI=
  db_pass: U3Ryb25nU0BwYXNzdzByZCE=
