apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  db_user: YXBwX3VzZXI= # Base64 encoded value of "app_user"
  db_pass: U3Ryb25nU0BwYXNzdzByZCE= # Base64 encoded value of "StrongP@ssw0rd!"
