apiVersion: apps/v1
kind: Deployment
metadata:
  name: seating-service
  labels:
    app: seating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seating-service
  template:
    metadata:
      labels:
        app: seating-service
    spec:
      containers:
        - name: seating-service
          image: seating-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: seating-db
            - name: DB_USER
              value: app_user
            - name: DB_PASS
              value: StrongP@ssw0rd!
---
apiVersion: v1
kind: Service
metadata:
  name: seating-service
spec:
  selector:
    app: seating-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
