apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:3005']
      - job_name: 'catalog-service'
        static_configs:
          - targets: ['catalog-service:3001']
      - job_name: 'seating-service'
        static_configs:
          - targets: ['seating-service:3002']
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:3003']
      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:3004']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
